### ISSUE TITLE
Spawn a "Makeover mage" NPC that will open the Player design interface

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#105]
Blocked by #64 and #94

**Comment by lare96** [comment]
How do you feel about it? Do you think the marketplace area would be a better place to have any NPCs we're going to spawn?

**Comment by jhg023** [comment]
It would probably make sense to spawn this specific NPC in the bank close to where a new player spawns for easy access, in my opinion.

**Comment by searledan** [comment]
Can this now be closed?

**Comment by lare96** [comment]
Yeah, forgot to do it. My bad!
