### ISSUE TITLE
Complete the wiki

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#115]
The wiki is an absolutely essential resource for people that need assistance. It needs to be completed. It's an easy (but time-consuming) job

**Comment by trinixgz** [comment]
Would definitely love to see this implemented. Finally figured out how to do it without any assistance, but definitely would streamline the process for people wishing to get on board and help!

**Comment by lare96** [comment]
This will be started once the scala-to-kotlin branch is merged with master!

**Comment by lare96** [comment]
Done!
