### ISSUE TITLE
Thieving Skill

### ISSUE THREAD

**Issue by AshotN** [luna-rs/luna#128]
I'm trying to learn the environment and develop the thieving skill, i'm using the fishing plugin as a reference. I'm wondering if I should use one of the current actions(HarvestAction), or would it be better of to create a new one for thieving. Stalls don't have a chance to fail(not counting guards stopping you) and they don't involve any item that needs to be removed. Any tips towards the right path would be appreciated.

**Comment by lare96** [comment]
Hey man. Since thieving isn't automated you actually don't even need to use an action. Just object and npc click events

**Comment by AshotN** [comment]
Ya I started figuring out no action was needed. I made a fork and got pickpocketing working. But I couldn’t get anything going with stalls because the server doesn’t receiver any object click event from clicking on stalls. 

I tried following the code all the way through, but I couldn’t figure out why stalls wouldn’t do anything besides a walk event. 

If you could check out my fork and see if I wrote the pickpocket well so far. I’d appreciate It

**Comment by lare96** [comment]
I sent you some comments. Looks great so far

**Comment by AshotN** [comment]
Sure. What’s the server

**Comment by lare96** [comment]
https://discord.gg/udCqykV

**Comment by lare96** [comment]
Closing since we've talked about this over discord already
