### ISSUE TITLE
Modify the computeBuyValue formula in the shop class

### ISSUE THREAD

**Issue by DukeCharles** [luna-rs/luna#153]
The current method used isnt reflective of the runescape 2006 version used.

- Must support special shop prices
- Prices must change according to item stock

**Comment by lare96** [comment]
How does the buy formula differ from your sell PR?

**Comment by DukeCharles** [comment]
It differ a bit in the sense that the price is the full value of the item and also I dont know if the stockdifferencial cap at 10 items
