### ISSUE TITLE
Improve Log4j2 usage & fix conventions

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#157]
Log4j2 is an amazing logging framework, but I'm not sure all of the advantages it offers are being taken advantage of. I think it could be improved by
- Renaming all instances of `LOGGER` to `logger`

- Using `DEBUG` and `TRACE` level logging more often

- Having the option to switch between `SIMPLE` and `VERBOSE` console log formatting 
`SIMPLE` would be one line per log
`VERBOSE` would be the classic two lined log
All file logging defaults to `SIMPLE` and can't be changed.

- Having ability to switch between `OUT, ERR, MIXED` logging output streams.
`OUT` would log all output to `System.out` (white text)
`ERR` would log all output to `System.err` (red text)
`MIXED` would log `TRACE, DEBUG, INFO` output to `System.out` and `WARN, ERROR, FATAL` to `System.err`

- Adding console, chat, command, item drop, and private message text file logs. All logs would be able to be set with whether they are logged to the console, a file, both, or none.

- Adding a `root_level` setting

**Comment by Zachac** [comment]
This seems fairly straightforward, I can start working on these features
