### ISSUE TITLE
Documentation for regions

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#164]
I'd love to see some wiki pages that thoroughly explain how regions work.

More specifically,
## General
- [ ] What is the scope of a region
- [ ] What is out of scope for a region

## Modifications
- [ ] How to modify existing regions
- [ ] How to add additional regions
- [ ] What assets/configurations do regions contain

## Integrations
- [ ] The relationship between regions/entities, and regions/chunks.
- [ ] Can regions communicate, if so why and how
- [ ] How region synchronization works

**Comment by notjuanortiz** [comment]
The code should be self-documenting. Closing this.

**Comment by lare96** [comment]
Feel free to make any changes to the documentation
