### ISSUE TITLE
Remove circular dependency between Player and GameClient

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#165]

**Comment by lare96** [comment]
This can be accomplished by adding a `Player player` argument for `GameClient` functions where the player instance is used. Then it can be removed from the constructor.

Would you like to take task on?

**Comment by notjuanortiz** [comment]
Sure.

**Comment by lare96** [comment]
An even easier way to solve that would be to move the `pendingLogout` boolean from the Player class to the GameClient class. Then it can be referenced from both the Player and LunaUpstreamHandler classes
