### ISSUE TITLE
Bump Kotlin from 1.3.11 to 1.3.50

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#170]
This should allow us to make use of parallel task execution included in 1.3.20 via `kotlin.parallel.tasks.in.project=true` within our build.gradle file.

Since 1.3.50, Kotlin scripting capabilities are now included of the box.
https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md

**Comment by lare96** [comment]
Fixed in 
72e1b14
