### ISSUE TITLE
Reduce coupling to LunaContext

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#185]
The coupling of the `LunaContext` onto unrelated objects such as `PluginManager`, `Entity`, and `LunaChannelInitializer` makes writing unit tests tedious and messy.

**Comment by lare96** [comment]
Does using Mockito mitigate those issues? It's already a dependency. If not, what's the solution you reccomend? Dependency injection?

**Comment by notjuanortiz** [comment]
Mocking objects would work in most cases but would be promote redundant code across test suites. 
Dependency injection would "reduce" coupling, kind of? It would actually make mocking required instead of optional. It would also increase the learning curve, and slow down the time-to-contribute since developers would have to learn how dependency injection works. For most cases, I would save DI for more enterprise applications, not for a small OSS project.

**Comment by notjuanortiz** [comment]
I think the best solution would be to make use of the singleton pattern. It should remove the need to store references of the object itself, resulting in slightly less memory consumption. It also makes testing more compact since we don't need to constantly mock the context and its properties.
