### ISSUE TITLE
Generate a unique event when someone removes a player from ignored list

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#191]

**Comment by lare96** [comment]
Is it not currently working? The code is here https://github.com/luna-rs/luna/blob/master/src/main/java/io/luna/net/msg/in/PrivateChatMessageReader.java

**Comment by notjuanortiz** [comment]
It does work but it is not extensible nor is it well-defined. If someone wanted to perform some task __only__ when a player removes someone from their ignored, they could just append that logic to this class. Though, if we kept adding features onto this class it would create a huge avoidable mess.

**Comment by lare96** [comment]
You the type of change is specified within the event
```kotlin
on(PrivateChatListChangeEvent::class).
  filter { type == ChangeType.REMOVE_IGNORE }.
  then { ... }  
```
? or are you referring to something else

**Comment by notjuanortiz** [comment]
Yes, but filtering is an extraneous operation that can be avoided by defining an event for each type.

```kotlin 
on(RemoveIgnoreEvent::class){ 
 doSomething() }

on(AddIgnoreEvent::class){ 
 doSomethingElse() }
```

Writing scripts in this fashion is much more clear and concise imo.

**Comment by lare96** [comment]
Okay, fair point.
