### ISSUE TITLE
Make  MobList#retrieve use Optional#ofNullable & update documentation

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#200]
The documentation for this method states that the method throws an exception when it does not.

**Comment by itzshahay** [comment]
it does
```
/**
 * Constructs an instance with the described value.
 *
 * @param value the non-{@code null} value to describe
 * @throws NullPointerException if value is {@code null}
 */
private Optional(T value) {
    this.value = Objects.requireNonNull(value);
}
```

**Comment by notjuanortiz** [comment]
You're absolutely right.

**Comment by lare96** [comment]
Looking at the method again it's a bit odd because it returns optional when the optional can never be empty in the first place. It should just return `E` by itself

```java
    public Optional<E> retrieve(int index) {
        return Optional.of(get(index));
    }
```

**Comment by notjuanortiz** [comment]
The optional can only throw a NPE (null pointer exception) when the array index is empty or out of bounds which would be thrown by the underlying array already.

 It is also confusing when to use `get` vs `retrieve`. I'm not convinced `retrieve` is even needed, unless `get` is made private making it clear that `retrieve` is the preferred method.

**Comment by lare96** [comment]
It can be used for when you prefer to have an optional instance rather than dealing with null
