### ISSUE TITLE
GroundItem expire times are in ticks not in minutes

### ISSUE THREAD

**Issue by Nubebuster** [luna-rs/luna#205]
GroundItem.java line 38-48 have the values for item expiration in minutes, but on GroundItem.java(92) the comparison is in ticks

**Comment by searledan** [comment]
@Nubebuster Can you provide code examples? 

The lines in GroundItem.java don't make sense from what I am looking at.

Line 38-48:

    /**
     * The current amount of expiration ticks.
     */
    private OptionalInt expireTicks = OptionalInt.of(0);

    /**
     * Creates a new {@link GroundItem}.
     *
     * @param context The context instance.
     * @param id The item identifier.


Line 92:
`
               toString();
`

**Comment by Nubebuster** [comment]
Excuse me,

I mean GroundItemList.java

**Comment by lare96** [comment]
@Nubebuster Sorry for the late reply but thanks for reporting this. Also there's no workaround for this AFAIK besides using two accounts :/ GitHub limitation
