### ISSUE TITLE
Cannot use DefinitionRepository outside of package

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#206]
# Issue
When trying to make use of any `DefinitionRepository` implementations __outside of the `io.luna.game.model.def` package__, I found myself unnecessarily importing the parent class (which is an abstract class).

I'm sure this was intentional but if we're going to move towards packaging by feature, this would be a good step towards making that possible.
### Current syntax
```java 
DefinitionRepository.ArrayDefinitionRepository repository = new DefinitionRepository.ArrayDefinitionRepository(0);
```

### Ideal syntax
```java 
ArrayDefinitionRepository repository = new ArrayDefinitionRepository(0);
```

**Comment by lare96** [comment]
This sounds like the right direction to go in.
