### ISSUE TITLE
Remove RegionPosition

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#213]
This class is no longer being used since it has been replaced with `ChunkPosition` and is due to be removed/deprecated.

**Comment by lare96** [comment]
`RegionPosition` differs from `ChunkPosition` in that it refers to a 64x64 area, whereas the latter refers to a 8x8 area

It's not used yet, but it will be used in the future for things like music (it has a field for the region ID)

**Comment by jhg023** [comment]
Because `8x8` fits perfectly into `64x64`, couldn't we use a mapping of region IDs to a set of `ChunkPosition` objects? That would allow us to still remove `RegionPosition`.

**Comment by lare96** [comment]
How would the other information, such as the region X and Y be accessible?

**Comment by jhg023** [comment]
Could we round down the `ChunkPosition#getX` and `ChunkPosition#getY` to the nearest multiple of `64`?
