### ISSUE TITLE
Consolidate logging settings into a single package

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#215]
# Problem
All configurations/settings related to logging are scattered throughout the project.

# Implementation
- [ ] Move `LoggingSettings`, and `LoggingConfigurationFactory` into a single package `io.luna.logging`
- [ ] Extract logging-related settings/configuration in Luna.class to a separate/multiple class(es), ^.

**Comment by lare96** [comment]
io.luna.logging has been removed
