### ISSUE TITLE
Move plugins.api into separate module

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#216]
# Problem
The plugins folder contains the API as well as kotlin plugins. By moving the API (we should rename this) into a separate module, this would contribute to #155 

# Implementation
Create gradle module `api` with a dependency on the `rootProject` and kotlin. 
Move api package from plugins folder into src/main/kotlin within the api module.

**Comment by lare96** [comment]
What do you suggest it be named other than API? I think that should be decided on before going forward

**Comment by notjuanortiz** [comment]
If the purpose of the library is to build on top of the existing infrastructure without exposing critical components like networking or the game loop, I think SDK (Software Development Kit) is a more appropriate term.

Here's some examples of existing plugin SDKs (not necessarily related to game development)
- https://www.jetbrains.org/intellij/sdk/docs/intro/welcome.html
- https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk/
- https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

**Comment by lare96** [comment]
Merge with #180
