### ISSUE TITLE
Make RDBMS-based persistence easier to set up

### ISSUE THREAD

**Issue by notjuanortiz** [luna-rs/luna#250]
# Problem
To get the SQLSerializer to work, I've had to manually create a few tables on my database.

# Solution
It would be nice to have a schema that I could just import to get things running quickly.

**Comment by notjuanortiz** [comment]
Atm there is no database specified during the connection initialization. Now I'm wondering if it's best to loosely support all databases (or at least the most common ones) or just one and optimize for it.

**Comment by lare96** [comment]
Schemas have been added and are available in data/net/sql
