### ISSUE TITLE
Update README with new Discord link

### ISSUE THREAD

**Issue by ryanabaker** [luna-rs/luna#333]
The link to the Discord in the README is invalid and should be updated.

![image](https://github.com/user-attachments/assets/e29336ce-8167-4d96-a8d1-7bffb5f42545)

**Comment by lare96** [comment]
Done, I'm sorry I didn't see this earlier, and also for the inactivity on the github page. Will get this issue section and PR section more organized so everyone can submit issues and PRs with confidence

**Comment by lare96** [comment]
Done, I'm sorry I didn't see this earlier, and also for the inactivity on the github page. Will get this issue section and PR section more organized so everyone can submit issues and PRs with confidence
