### ISSUE TITLE
Consider decoupling source code into modules

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#56]
The package hierarchy is getting pretty insane. I think it may look a lot nicer and easier to navigate if it's split up into different modules.

**Comment by lare96** [comment]
3 or 4 modules would do nicely. Maybe: luna-main, luna-game, luna-net, luna-utils

**Comment by tlf30** [comment]
Honestly, I find projects that do that more confusing to try and work on. Mostly because it is done unnecessarily. Having a large package structure is not a bad things as long as it is organized. We have projects at work with hundreds of packages in a single project.
