### ISSUE TITLE
Use a different TOML parser library

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#58]
[toml4j](https://github.com/mwanji/toml4j) is outdated. The current specification is 0.5.0 and toml4j currently only supports 0.4.0. The project hasn't been updated for a year so another parser will need to be found to replace it. Needs to be looked into ASAP since important parts of Luna depend on TOML.

**Comment by AshotN** [comment]
How about https://github.com/TheElectronWill/Night-Config

**Comment by lare96** [comment]
Will definitely consider that!

**Comment by lare96** [comment]
Will stick with toml4j for now as I still see some activity but if anything will use night-config in the future.
