### ISSUE TITLE
Decouple plugin GUI from server code, if possible

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#73]

**Comment by lare96** [comment]
@jhg023 could this be done with Java 9+ modules? Or would it be better to just completely decouple it into its own project. The plan once Luna is stable, is to incorporate a plugin repository where users can install their own plugins

**Comment by lare96** [comment]
Will just ship it with Luna for 1.0

**Comment by notjuanortiz** [comment]
In order for the GUI to work as a stand-alone application, it would need to import the server as a library. Which means, at least in my mind, we'd need to publish the server's build artifacts to a maven repository like JCenter or Maven Central. This opens up the possibility for developers to create their own tools on top of the server. 

That being said, this feature indirectly broadens the scope of the project. @lare96 Is this the direction that you want to go in?

**Comment by lare96** [comment]
I was thinking that the GUI would be imported into Luna as a maven artifact or local JAR, then the implementation could be added

```java
if(Luna.settings().pluginGui()) {
    var impl = new PluginWindowListener(pluginMap, ..., ...);
    var window = new PluginWindow(impl);
    window.open();
}
```

**Comment by notjuanortiz** [comment]
I'm not a fan of having GUI components tightly coupled to the server logic. If a developer doesn't want the GUI, he/she shouldn't be forced to download it unnecessarily. Like I said earlier, if instead we were to export Luna modules as maven artifacts, then we could achieve the same result. An unintended benefit of this approach is that it would open up the possibility for other application-wide extensions.

Now the implementation of such a design would be a bit more complex than the sample code you provided but I'm positive we're able to come up with an intuitive solution.
