### ISSUE TITLE
Make ItemContainer more efficient, and test for bugs

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#80]

**Comment by jhg023** [comment]
When I was active in RS a few years ago, I wrote a container system (that was similar to other servers') but improved on the time complexity of most operations. I'll upload the file here, but I think it can be improved further if I take some time to redesign it.
[Container.txt](https://github.com/luna-rs/luna/files/2498552/Container.txt)

**Comment by lare96** [comment]
Are there any specific bottlenecks that you notice now, after the most recent commits?

**Comment by jhg023** [comment]
@lare96  Have you seen the PR I created about a week ago? #83 

I'd have to recreate it with the updates you've added, but my goal was to essentially eliminate iteration over the container, as well as using a library that supports primitive collections (which will give a good speedup over the current implementation).

**Comment by lare96** [comment]
I've just taken a look. Are the improvements substantial enough to warrant a large change? Most of the lookups are either in a container with a small capacity (< 40), finish before fully traversing (index lookups), or are invoked sparingly to begin with

**Comment by jhg023** [comment]
@lare96 I'd argue yes, as the primitive collections can also be used elsewhere throughout the project. The changes allow for scalable containers in the case that container size is ever changed (such as bank size) either in Luna or in an implementation created by someone else.

I also wouldn't considered this a large change, as modifications were only made to a single class (as well as the `pom.xml`).

**Comment by jhg023** [comment]
I've opted for `fastutil`, and there's a ton of benchmarks online, such as [this one](http://java-performance.info/hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove-january-2015/). If needed, I'll take some myself with JMH using both versions of `ItemContainer`.

**Comment by lare96** [comment]
The early bottlenecks this issue is referring to (re-displaying the whole container for a single item update, bank shifting, some lookups, etc.) have been fixed. I think I'll close this so that we can move onto adding Java 11 support. @jhg023 If you benchmark and find any bottlenecks anywhere else please open up another issue!
